crowdproject/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
  path('trails/', include('trails.urls')),
  path('admin/', admin.site.urls),
]

trails/urls.py
from django.urls import path
from . import views

urlpatterns = [
  path('', views.index, name='index'),
  path('regions/', views.regions, name='regions'),

  path('list/', views.trail_list, name='trail_list'),
  path('reports/', views.reports_list, name='reports_list'),
  path('reports/day/<str:day>', views.reports_day, name='reports_day'),
  path('reports/time/<str:period>', views.reports_time, name='reports_time'),

  path('<slug:region_slug>/', views.trails, name='trails'),
  path('<slug:region_slug>/<slug:trail_slug>/', views.trailheads, name='trailheads'),

  #TODO
  path('<slug:region_slug>/<slug:trail_slug>/summary', views.trail_summary, name='trail_summary'),
  #

  path('<slug:region_slug>/trailheads/bathroom/', views.trailheads_filter_bathroom, name='trailheads_filter_bathroom'),
  path('<slug:region_slug>/trailheads/access/', views.trailheads_filter_access, name='trailheads_filter_access'),
  
  path('<slug:region_slug>/<slug:trailhead_slug>/reports', views.reports_trailhead, name='reports_trailhead'),
  path('<slug:region_slug>/<slug:trail_slug>/reports/', views.reports_trail, name='reports_trail'),
  path('<slug:region_slug>/<slug:trail_slug>/<slug:trailhead_slug>/reports/', views.reports_trail_trailhead, name='reports_trail_trailhead'),

  path('<slug:region_slug>/<slug:trail_slug>/<slug:trailhead_slug>/<str:report>/', views.report, name='report'),

  path('<slug:region_slug>/<slug:trail_slug>/filtering/', views.reports_filter, name='reports_filter'),
  path('<slug:region_slug>/<slug:trail_slug>/day/<str:day>', views.reports_trail_day, name='reports_trail_day'),
  path('<slug:region_slug>/<slug:trail_slug>/time/<str:period>', views.reports_trail_time, name='reports_trail_time')
]

trails/models.py
from django.core import validators
from django.db import models
from django.urls import reverse
import uuid
from django.core.validators import MinValueValidator, MaxValueValidator
from django.utils.text import slugify

class Region(models.Model):
  def __str__(self):
    return self.name

  REGION_CHOICES = [
    ('OP', 'Olympic Peninsula'),
    ('NC', 'North Cascades'),
    ('CC', 'Central Cascades'),
    ('SQ', 'Snoqualmie'),
    ('SC', 'South Cascades'),
    ('WW', 'Western Washington Lowlands'),
    ('EW', 'Eastern Washington'),
    ('CW', 'Central Washington'),
    ('SW', 'Southwest Washington'),
  ]

  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  name = models.CharField(
    choices=REGION_CHOICES,
    max_length=2, 
    unique=True, 
    help_text='Region Name'
  )
  region_slug = models.SlugField(null=True, verbose_name="Slug")

  def save(self, *args, **kwargs):
    self.region_slug = self.region_slug or slugify(self.name)
    super().save(*args, **kwargs)

class Trail(models.Model):
  def __str__(self):
    return self.name

  def get_id(self):
    return self.id

  region = models.ForeignKey(Region, on_delete=models.CASCADE)
  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  modified = models.DateTimeField('time modified', auto_now=True)
  trail_slug = models.SlugField(null=True, verbose_name="Slug")

  name = models.CharField(max_length=100, unique=True, help_text='Trail Name')
  coordinates = models.CharField(
    max_length=25,
    help_text='Geographic coordinates searchable via Google Maps'
  )
  length_json = models.JSONField('Trail length', blank=True, null=True,
    help_text='From 0.1 to 999.9 miles'
  )
  elevation_gain_json = models.JSONField('Elevation Gain', blank=True, null=True,
    help_text='From trailhead to highest point of trail',
  )
  dogs_allowed = models.JSONField('Dogs', blank=True, null=True, default=list)
  horses_allowed = models.JSONField('Horses', blank=True, null=True, default=list)

  def save(self, *args, **kwargs):
    self.trail_slug = self.trail_slug or slugify(self.name)
    super().save(*args, **kwargs)

class Trailhead(models.Model):
  def __str__(self):
    return self.name

  PARKING_TYPES = [
    ('UL', 'Unpaved Lot'),
    ('PL', 'Paved Lot'),
    ('S', 'Street/Road'),
    ('P', 'Designated Pullout/Shoulder')
  ]

  ACCESS_TYPES = [
    ('FS', 'Forest Service Road'),
    ('P', 'Paved Road'),
  ]

  BATHROOM_STATUS = [
    ('O', 'Open'),
    ('C', 'Closed'),
  ]

  BATHROOM_TYPE = [
    ('P', 'Portable/Outhouse'),
    ('FP', 'Fixed Building, Pit'),
    ('FR', 'Fixed Building with plumbing')
  ]

  ACCESS_CONDITIONS = [
    ('I', 'Impassable'),
    ('P+', 'Many potholes'),
    ('P', 'Potholes'),
    ('P-', 'Occasional potholes'),
    ('G', 'Good')
  ]

  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  region = models.ForeignKey(Region, on_delete=models.CASCADE)
  trails = models.ManyToManyField(Trail, related_name='trailheads')
  modified = models.DateTimeField('time modified', auto_now=True)
  trailhead_slug = models.SlugField(null=True, verbose_name="Slug")

  name = models.CharField(max_length=50, unique=True, help_text='Name of Trailhead')
  coordinates = models.CharField(
    max_length=25,
    help_text='Geographic coordinates searchable via Google Maps'
  )

  access = models.CharField(
    max_length=2, blank=True, null=True,
    choices=ACCESS_TYPES,
    help_text='How is the trailhead accessed?'
  )
  access_distance = models.DecimalField(
    max_digits=3, decimal_places=1,
    blank=True, null=True,
    help_text='If accessed via service road, length of service road from paved road to trailhead',
    validators=[MinValueValidator(0.1)]
  )
  access_condition = models.CharField('Road access condition',
    max_length=2, blank=True, null=True,
    choices=ACCESS_CONDITIONS,
    help_text='Condition of road to trailhead'
  )
  pkg_type = models.CharField('Parking type',
    max_length=2, blank=True, null=True,
    choices=PARKING_TYPES,
    help_text='Type of Parking at Trailhead'
  )
  pkg_capacity = models.IntegerField('Parking capacity', 
    blank=True, null=True,
    help_text='Approximate number of cars capable of parking at trailhead lot',
    validators=[MinValueValidator(0)]
  )
  bathroom_type = models.CharField(
    blank=True, null=True,
    max_length=2, 
    choices=BATHROOM_TYPE,
    help_text='Is there a bathroom at the trailhead?'
  )
  bathroom_status = models.CharField(
    blank=True, null=True,
    max_length=1, 
    choices=BATHROOM_STATUS,
    help_text='Is the bathroom open?'
  )

  def save(self, *args, **kwargs):
    self.trailhead_slug = self.trailhead_slug or slugify(self.name)
    super().save(*args, **kwargs)

class Report(models.Model):
  def __str__(self):
    return str(self.modified)

  def get_trailhead(self):
    return self.trailhead.name
  
  def get_trail(self):
    return self.trail.name

  PARKING_TYPES = [
    ('UL', 'Unpaved Lot'),
    ('PL', 'Paved Lot'),
    ('S', 'Street/Road'),
    ('P', 'Designated Pullout/Shoulder')
  ]

  DAYS = [
    ('M', 'Monday'),
    ('T', 'Tuesday'),
    ('W', 'Wednesday'),
    ('Th', 'Thursday'),
    ('F', 'Friday'),
    ('S', 'Saturday'),
    ('Su', 'Sunday')
  ]

  CAR_TYPES = [
    ('Suv', 'SUV'),
    ('S', 'Sedan'),
    ('T', 'Truck'),
    ('4wd', 'Four-wheel drive')
  ]

  ACCESS_TYPES = [
    ('FS', 'Forest Service Road'),
    ('P', 'Paved Road'),
  ]

  ACCESS_CONDITIONS = [
    ('I', 'Impassable'),
    ('P+', 'Many potholes'),
    ('P', 'Potholes'),
    ('P-', 'Occasional potholes'),
    ('G', 'Good')
  ]

  BATHROOM_STATUS = [
    ('O', 'Open'),
    ('C', 'Closed'),
  ]

  BATHROOM_TYPE = [
    ('P', 'Portable/Outhouse'),
    ('FP', 'Fixed Building, Pit'),
    ('FR', 'Fixed Building with plumbing')
  ]

  WEATHER_TYPE = [
    ('R', 'Rain'),
    ('Sn', 'Snow'),
    ('S', 'Sun'),
    ('PC', 'Partly Cloudy'),
    ('O', 'Overcast')
  ]

  TEMPERATURES = [
    ('F', '< 32'),
    ('C', '33-50'),
    ('N', '51-70'),
    ('W', '71-85'),
    ('H', '86-100'),
    ('E', '100 <')
  ]

  id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
  trail = models.ForeignKey(Trail, on_delete=models.CASCADE)
  trailhead = models.ForeignKey(Trailhead, on_delete=models.CASCADE)
  region = models.ForeignKey(Region, on_delete=models.CASCADE)

  created = models.DateTimeField('time created', auto_now_add=True)
  modified = models.DateTimeField('time modified', auto_now=True)

  length = models.DecimalField(
    max_digits=4, decimal_places=1, help_text='From 0.1 to 999.9 miles', blank=True, null=True,
    validators=[MinValueValidator(0.1)]
  )
  elevation_gain = models.IntegerField('Elevation Gain', 
    blank=True, null=True,
    help_text='From trailhead to highest point of trail',
    validators=[MinValueValidator(0)]
  )

  date_hiked = models.DateField(help_text='What date was the hike?')
  day_hiked = models.CharField(
    max_length=2,
    choices=DAYS,
    help_text='What day of the week was the hike?'
  )
  weather_type = models.CharField(
    max_length=2, blank=True, null=True,
    choices=WEATHER_TYPE,
    help_text='What was the weather like?'
  )
  temperature = models.CharField(
    blank=True, null=True,
    max_length=1,
    choices=TEMPERATURES,
    help_text='What was the temperature?'
  )
  car_type = models.CharField(
    max_length=3, blank=True, null=True,
    choices=CAR_TYPES,
    help_text='With what type of car did you access the trail?'
  )
  access = models.CharField(
    max_length=2, blank=True, null=True,
    choices=ACCESS_TYPES,
    help_text='How is the trailhead accessed?'
  )
  access_distance = models.DecimalField(
    max_digits=3, decimal_places=1,
    blank=True, null=True,
    help_text='If accessed via service road, length of service road from paved road to trailhead',
    validators=[MinValueValidator(0.1)]
  )
  access_condition = models.CharField(
    blank=True, null=True,
    max_length=2,
    choices=ACCESS_CONDITIONS,
    help_text='What is the condition of the road access to trailhead?'
  )
  trail_begin = models.TimeField(help_text='What time did the hike begin?')
  trail_end = models.TimeField(help_text='What time did the hike end?')
  bathroom_type = models.CharField(
    blank=True, null=True,
    max_length=2, 
    choices=BATHROOM_TYPE,
    help_text='Is there a bathroom at the trailhead?'
  )
  bathroom_status = models.CharField(
    blank=True, null=True,
    max_length=1, 
    choices=BATHROOM_STATUS,
    help_text='Is the bathroom open?'
  )
  pkg_location = models.CharField('Type of Parking',
    max_length=2,
    choices=PARKING_TYPES,
    help_text='Where did you park at the trailhead?'
  )
  pkg_estimate_begin = models.IntegerField(
    'Percentage Capacity Start',
    help_text='Approximate parking capacity full at trailhead arrival',
    validators=[MinValueValidator(0), MaxValueValidator(100)]
  )
  pkg_estimate_end = models.IntegerField(
    'Percentage Capacity End',
    help_text='Approximate parking capacity full at trailhead departure',
    validators=[MinValueValidator(0), MaxValueValidator(100)]
  )
  cars_seen = models.IntegerField(
    'Cars seen', help_text='Most cars seen at arrival/departure',
    validators=[MinValueValidator(0)]
  )
  people_seen = models.IntegerField(
    'People seen', help_text='Approximate number of people encountered on trail',
    validators=[MinValueValidator(0)]
  )
  horses_seen = models.BooleanField(blank=True, null=True)
  dogs_seen = models.BooleanField(blank=True, null=True)

trails/forms.py
from django.forms import ModelForm, SelectDateWidget, Form, ChoiceField, TextInput
from .models import Trail, Trailhead, Report
from datetime import datetime

class TrailForm(ModelForm):
  class Meta:
    model = Trail
    fields = ['region', 'name', 'coordinates']

class TrailheadForm(ModelForm):
  class Meta:
    model = Trailhead
    fields = ('region', 'trails', 'name', 'coordinates')

class TrailheadAssociationForm(ModelForm):
  class Meta:
    model = Trailhead
    fields = ('name',)

class ReportForm(ModelForm):
  class Meta:
    year_choices = []
    current_year = datetime.today().year
    for i in range(10):
      year_choices.append(current_year - i)

    model = Report
    fields = ('region', 'trail', 'trailhead', 'date_hiked', 'day_hiked', 'length', 'elevation_gain', 'weather_type', 'temperature', 
              'car_type', 'access', 'access_distance', 'access_condition', 'trail_begin', 'trail_end', 'bathroom_type', 'bathroom_status', 
              'pkg_location', 'pkg_estimate_begin', 'pkg_estimate_end', 'cars_seen', 'people_seen', 'horses_seen', 'dogs_seen')
    widgets = {
      'date_hiked': SelectDateWidget(
        years=year_choices,
        empty_label=("Year", "Month", "Day")
      ),
    }

class SelectDayForm(Form):
  DAYS = [
    ('', 'Day'),
    ('M', 'Monday'),
    ('T', 'Tuesday'),
    ('W', 'Wednesday'),
    ('Th', 'Thursday'),
    ('F', 'Friday'),
    ('S', 'Saturday'),
    ('Su', 'Sunday')
  ]

  days_field = ChoiceField(choices = DAYS, label='')

class SelectTimeForm(Form):
  TIME = [
    ('', 'Time'),
    ('early morning', 'Early morning'),
    ('mid morning', 'Mid-morning'),
    ('late morning', 'Late morning'),
    ('afternoon', 'Afternoon'),
    ('evening', 'Evening'),
    ('overnight', 'Overnight')
  ]

  time_field = ChoiceField(choices = TIME, label='')

trails/templates/trails/button.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'trails/button.css' %}">

<!DOCTYPE html>
<html>
  <body>
    <div id="back-button"><a href="{{ link }}"><-Back</a></div>
  </body>
</html>

trails/templates/trails/report.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'trails/report.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'trails/base_style.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Report</title>
  </head>
  <body>
    {% include "./header.html" %}
    {% if report %}
    <div class="subheader">
      <h2>
        <a href="{% url 'trails' slugs.region %}">{{ report.region.get_name_display }}</a> | 
        <a href="{% url 'trailheads' region_slug=slugs.region trail_slug=slugs.trail %}">{{ report.trail.name }}</a> |
        <a href="{% url 'reports_trail_trailhead' region_slug=slugs.region trail_slug=slugs.trail trailhead_slug=slugs.trailhead %}">{{ report.trailhead.name }}</a>
      </h2>
    </div>
    {% endif %}
    <div id="report-table">
      <table>
        <tbody>
          <tr><th colspan="3">Report</th></tr>
          <tr>
            <td>Time</td>
            <td>Date: {{ report.date_hiked }}</td>
            <td>Day: {{ report.get_day_hiked_display }}</td>
          </tr>
          <tr>
            <td>Duration</td>
            <td>Started hike: {{ report.trail_begin }}</td>
            <td>Ended hike: {{ report.trail_end }}</td>
          </tr>
          <tr><th colspan="3">Trailhead Features</th></tr>
          <tr>
            <td>Access</td>
            <td colspan="2">
              {% if report.access %}{{ report.get_access_display }}
              {% else %}No Data{% endif %}
            </td>
          </tr>
          <tr>
            <td>Parking</td>
            <td colspan="2">
              {% if report.pkg_location %}{{ report.get_pkg_location_display }}
              {% else %}No Data{% endif %}
            </td>
          </tr>
          <tr>
            <td>Bathroom</td>
            <td colspan="2">
              {% if report.bathroom_type %}{{ report.get_bathroom_type_display }} - {{ report.get_bathroom_status_display }}
              {% else %}No Data{% endif %}
            </td>
          </tr>
          <tr><th colspan="3">Trail Conditions</th></tr>
          <tr>
            <td>Parking</td>
            <td>Parking full on arrival: {{ report.pkg_estimate_begin }}%</td>
            <td>Parking full on departure: {{ report.pkg_estimate_end }}%</td>
          </tr>
          <tr>
            <td>People</td>
            <td>Most cars seen at trailhead: {{ report.cars_seen }}</td>
            <td>Estimated people seen on trail: {{ report.people_seen }}</td>
          </tr>
          <tr>
            <td>Animals</td>
            <td>Dogs Seen: {% if report.dogs_seen %} Yes {% else %} No {% endif %}</td>
            <td>Horses Seen: {% if report.horses_seen %} Yes {% else %} No {% endif %}</td>
          </tr>
        </tbody>
      </table>
    {% url 'reports_trail_trailhead' region_slug=slugs.region trail_slug=slugs.trail trailhead_slug=slugs.trailhead as link %}
    {% include "./button.html" with link=link %}
    </div>
  </body>
</html>

trails/templates/trails/reports.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'trails/base_style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'trails/feeds.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'trails/forms.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Reports</title>
  </head>
  <body>
    {% include "./header.html" %}
    <div class="subheader">
    {% if trail %}
      <h2>
        <a href="{% url 'trails' trail.region %}">{{ trail.region.get_name_display }}</a> | 
        {{ trail.name }}
      </h2>
    {% elif trailhead %}
      <h2>
        <a href="{% url 'trails' trailhead.region.id %}">{{ trailhead.region.get_name_display }}</a> | 
        <a href="{% url 'trailheads' region=trailhead.region.id trail=trail_obj.id %}">{{ trail_obj.name }}</a> | 
        {{ trailhead.name }}
      </h2>
    {% elif day %}
      {% if advice %}
      <h2>
        <a href="{% url 'trails' reports_list.0.trail.region %}">{{ reports_list.0.region.get_name_display }}</a> |
         <a href="{% url 'trailheads' region=reports_list.0.trail.region trail=reports_list.0.trail.id %}">{{ reports_list.0.trail.name }}</a> | 
        {{ reports_list.0.get_day_hiked_display }}
      </h2>
      {% else %}
      <h2>
        <a href="{% url 'trails' region %}">{{ trail_day_empty.region.get_name_display }}</a> | 
        <a href="{% url 'trailheads' region=region trail=trail_day_empty.id %}">{{ trail_day_empty.name }}</a> | 
        {{ day }}
      </h2>
      {% endif %}
    {% elif period %}
      {% if advice %}
      <h2>
        <a href="{% url 'trails' reports_list.0.trail.region %}">{{ reports_list.0.region.get_name_display }}</a> | 
        <a href="{% url 'trailheads' region=reports_list.0.trail.region trail=reports_list.0.trail.id %}">{{ reports_list.0.trail.name }}</a> | 
        {{ period }}
      </h2>
      {% else %}
      <h2>
        <a href="{% url 'trails' region %}">{{ trail_time_empty.region.get_name_display }}</a> | 
        <a href="{% url 'trailheads' region=region trail=trail_time_empty.id %}">{{ trail_time_empty.name }}</a> | 
        {{ period }}
      </h2>
      {% endif %}
    {% endif %}
    </div>

    <div class="report">
    {% if reports_list %}
      {% if reports_total %}
      <div id="advice" class="{{ caution }}">
        <p>{{ reports_list_total }} out of {{ reports_total }} total submitted</p>
        <p>{{ advice }}</p>
      </div>
      {% endif %}
      <div class="trail-table">
        <h3>Reports ({{ reports_list.count }})</h3>
        <table>
          <thead>
            <tr>
              {% if not trailhead %}<td>Trailhead</td>{% endif %}
              <td>Date Hiked</td>
              <td>Day Hiked</td>
              {% if period %}<td>Time Hiked</td>{% endif %}
              <td>Details</td>
            </tr>
          </thead>
          <tbody>
          {% for report in reports_list %}
            <tr>
              {% if not trailhead %}
              <td>
                <a href="{% url 'reports_trailhead' region=report.trail.region trail=report.trail.id trailhead=report.trailhead.id %}">{{ report.trailhead.name }}</a>
              </td>
              {% endif %}

              {% if date == report.date_hiked %}
                <td>Today</td>
              {% else %}
                <td>{{ report.date_hiked }}</td>
              {% endif %}
              <td>{{ report.get_day_hiked_display }}</td>

              {% if period %}
                <td>{{ report.trail_begin }} - {{ report.trail_end }}</td> 
              {% endif %}

              {% if trail %}
              <td>
                <a href="{% url 'report' region=region trail=trail.id trailhead=report.trailhead.id report=report.id %}">More</a>
              </td>
              {% elif trailhead %}
              <td>
                <a href="{% url 'report' region=region trail=trail_obj.id trailhead=trailhead.id report=report.id %}">More</a>
              </td>
              {% else %}
              <td>
                <a href="{% url 'report' region=report.trail.region trail=report.trail.id trailhead=report.trailhead.id report=report.id %}">More</a>
              </td>
              {% endif %}
            </div>
          {% endfor %}
          </tbody>
        </table>
      </div>
    {% else %}
      <p>No reports found</p>
      {% if reports_total %}
        <p><span>Note</span> - There have been <span>{{ reports_total }}</span> submitted for this trail. If there have not been many reports, there may not be enough data to determine popularity.</p>
      {% endif %}
    {% endif %}
    {% if trail %}
    <div class="report-footer">
      <p>To add a report, select a <a href="{% url 'trailheads' region=trail.region trail=trail.id %}">trailhead</a></p>
    </div>
    {% endif %}
    </div>

    {% if trailhead %}
    <div class="form-box">
      <h4>Add Report</h4>
      <form action="{% url 'reports_trailhead' region trail_obj.id trailhead.id %}" method="post">
        {% csrf_token %}
        {{ form.non_field_errors }}
        {% for field in form %}
          <div class="field">
            {% if field.field.required %}
              <p class="label"><span>*</span> {{ field.label_tag }}</p>
            {% else %}
              {{ field.label_tag }}
            {% endif %}

            <div>{{ field }}</div>
            {% if field.help_text %}
              <p>{{ field.help_text|safe }}</p>
            {% endif %}
            {{ field.errors }}
          </div>
        {% endfor %}
        <input class="button" type="submit" value="Add">
      </form>
    </div>
    {% endif %}
  </body>
</html>

trails/templates/trails/trail-summary.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'trails/base_style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'trails/trail_summary.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Trail Summary</title>
  </head>
  <body>
    {% include "./header.html" %}
    <div class="subheader">
      <h2>
        <a href="{% url 'trails' region.region_slug %}">{{ region.get_name_display }}</a> | 
        {{ trail.name }} - Report of Reports
      </h2>
    </div>
    {% if summary %}
    <div>
      <h4>Facilities and Access</h4>
      <p>Trailheads: {{ trailheads.obj.count }}</p>

      <ul>
      {% for trailhead in trailheads.obj %}
        <li>{{ trailhead.name }} - <span>via {{ trailhead.get_access_display }}</span> |
          <span>{{ trailhead.get_bathroom_type_display }} - <span id="bathroom_status">{{ trailhead.get_bathroom_status_display }}</span></span>
        </li>
      {% endfor %}
      </ul>

      <h4>Popularity</h4>
      <p>{{ summary.reports_trail_count }} reports of {{ summary.reports_region_count }} total posted for {{ region.get_name_display }}</p>
    </div>
    {% endif %}
    {% url 'trailheads' region_slug=region.region_slug trail_slug=trail.trail_slug as link %}
    {% include "./button.html" with link=link %}
  </body>
</html>

trails/templates/trails/trailheads_filter.html
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'trails/base_style.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'trails/feeds.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'trails/forms.css' %}">

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Trailheads - Find</title>
  </head>
  <body>
    {% include "./header.html" %}
    <div class="subheader">
      {% if trailheads_list %}
        {% if type == 'bathroom' %}
          <h2>
            <a href="{% url 'trails' region.region_slug %}">{{ region.get_name_display }}</a> | 
            Trailheads - Open Bathrooms
          </h2>
        {% elif type == 'access' %}
          <h2>
            <a href="{% url 'trails' region.region_slug %}">{{ region.get_name_display }}</a> | 
            Trailheads - Paved Access
          </h2>
        {% endif %}
      {% else %}
        {% if type == 'bathroom' %}
          <h2><a href="{% url 'trails' region.region_slug %}">{{ region.get_name_display }}</a> | Trailheads - Open Bathrooms</h2>
        {% else %}
          <h2><a href="{% url 'trails' region.region_slug %}">{{ region.get_name_display }}</a> | Trailheads - Paved Access</h2>
        {% endif %}
      {% endif %}
    </div>
    {% if trailheads_list %}
    <div class="trail-table">
      <table>
        <thead>
          <tr>
            <td>Trailhead</td>
            <td>Trails</td>
            <td>Location</td>
            {% if type == 'bathroom' %}
              <td>Bathroom</td>
            {% elif type == 'access' %}
              <td>Access</td>
            {% endif %}
            <td>Updated</td>
            <td>Reports</td>
          </tr>
        </thead>
        <tbody>
          {% for trailhead in trailheads_list %}
            <tr>
              <td>
                <a href="{% url 'reports_trailhead' region_slug=region.region_slug trailhead_slug=trailhead.trailhead_slug %}">{{ trailhead.name }}</a>
              </td>
              <td>
                {% for trail_trailhead in trailhead.trails.all %}
                  <a href="{% url 'reports_trail' region_slug=region.region_slug trail_slug=trail_trailhead.trail_slug %}">{{ trail_trailhead.name }}</a>
                {% endfor %}
              </td>
              <td>{{ trailhead.coordinates }}</td>
              {% if type == 'bathroom' %}<td>{{ trailhead.get_bathroom_type_display }}</td>
              {% elif type == 'access' %}<td>{{ trailhead.get_access_display }}</td>
              {% endif %}
              {% if date == trailhead.modified.date %}
                <td>Today</td>
              {% else %}
                <td>{{ trailhead.modified|date:"m/d/y" }}</td>
              {% endif %}
              <td>{{ trailhead.report__count }}</td>
            </li>
          {% endfor %}
        </tbody>
      </table>
    </div>
    {% else %}
      <p>No trailheads found</p>
    {% endif %}
    {% url 'trails' region.region_slug as link %}
    {% include "./button.html" with link=link %}
  </body>
</html>